name: vertx-hazelcast (5.x)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 5 * * *'
jobs:
  IT:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 21 ]
        hz: [ 5.4.0, 5.5.0 ]
        include:
          - os: ubuntu-latest
            jdk: 11
            hz: 5.3.8
    uses: ./.github/workflows/it.yml
    with:
      branch: ${{ github.event.pull_request.head.sha || github.ref_name }}
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
      hz: ${{ matrix.hz }}
    secrets: inherit
